[package]
name = "pq-vector"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "57.2.0"
async-trait = "0.1"
base64 = "0.22"
datafusion = "52.0.0"
parquet = "57.2.0"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }

[patch.crates-io]
datafusion = { git = "https://github.com/apache/datafusion.git" }
datafusion-catalog = { git = "https://github.com/apache/datafusion.git" }
datafusion-common = { git = "https://github.com/apache/datafusion.git" }
datafusion-expr = { git = "https://github.com/apache/datafusion.git" }
datafusion-functions = { git = "https://github.com/apache/datafusion.git" }
datafusion-functions-nested = { git = "https://github.com/apache/datafusion.git" }
datafusion-optimizer = { git = "https://github.com/apache/datafusion.git" }
datafusion-physical-expr = { git = "https://github.com/apache/datafusion.git" }
datafusion-physical-plan = { git = "https://github.com/apache/datafusion.git" }
datafusion-sql = { git = "https://github.com/apache/datafusion.git" }
