[package]
name = "pq-vector"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "57.2.0"
datafusion = "52.0.0"
parquet = "57.2.0"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
